version: '3.3'

services:
  demoapp:
    image: ghcr.io/benc-uk/nodejs-demoapp:latest
    container_name: demoapp
    restart: unless-stopped
    ports:
      - "3000:3000"
  
  node_exporter_demoapp:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter_demoapp
    command:
      - '--path.rootfs=/host'
    pid: host
    ports:
      - "9100:9100"
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

  cadvisor_demoapp:
    image: gcr.io/cadvisor/cadvisor:v0.45.0     
    container_name: cadvisor_demoapp
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    restart: unless-stopped
    privileged: true
